### ISSUE TITLE
Where does CAPSLOCK come from?

### ISSUE THREAD

**Issue by leonerd** [coldfix/setcapslock#2]
Less an issue and more of a plain question - where does the magic value for the capslock modifier come from?

https://github.com/coldfix/setcapslock/blob/master/setcapslock.c#L8

I see you've hardcoded it to 2 (i.e. `(1<<1)`) and it happens to work for me also, but I'm dubious as to where it comes from.

**Comment by coldfix** [comment]
Hey! Good question. I *think*, this is due to `LockMask` in `X11/X.h`:

```C
/* Key masks. Used as modifiers to GrabButton and GrabKey, results of QueryPointer,
   state in various key-, mouse-, and button-related events. */

#define ShiftMask		(1<<0)
#define LockMask		(1<<1)
#define ControlMask		(1<<2)
#define Mod1Mask		(1<<3)
#define Mod2Mask		(1<<4)
#define Mod3Mask		(1<<5)
#define Mod4Mask		(1<<6)
#define Mod5Mask		(1<<7)

/* modifier names.  Used to build a SetModifierMapping request or
   to read a GetModifierMapping request.  These correspond to the
   masks defined above. */
#define ShiftMapIndex		0
#define LockMapIndex		1
#define ControlMapIndex		2
#define Mod1MapIndex		3
#define Mod2MapIndex		4
#define Mod3MapIndex		5
#define Mod4MapIndex		6
#define Mod5MapIndex		7
```

I checked level 0 (Shift), 1 (CapsLock), 2 (Control), 3 (Left-Alt), 6 (Mod4/Windows/Super), 7 (Mod5/AltGr/Right-Alt) which is consistent with the definitions here. (I wouldn't recommend trying those unprepared, these are even less fun than capslock!)

But to be completely honest, I copied the constant from other web sources back then, e.g. [here](https://logixoul.wordpress.com/2008/08/14/how-to-set-leds-in-x-even-on-ubuntu/), [here](https://jatindhankhar.in/blog/xlib-blink-keyboard-led/) or [here](http://askubuntu.com/questions/80254/how-do-i-turn-off-caps-lock-the-lock-not-the-key-by-command-line/80301) and just made it into a small utility easy to install without deeper understanding. For a more worked out approach, see the [numlockx source](https://github.com/rg3/numlockx/blob/master/main.c), which deals with symbolic names of virtual modifier levels. So, maybe the numlockx devs know more about this topic.

**Comment by leonerd** [comment]
Ahhh; I seeee. It's called `Lock`, not `CapsLock`, which is why I didn't find it.

As to numlockx - yes, that's what I'm asking for in fact. numlockx doesn't currently do capslock, because capslock doesn't *have* an atom name, it's hardcoded. I was looking for the constant in a header file that would contain it, hence my question.
